#!/usr/bin/env bash
# Configure a Nginx server so that /redirect_me is redirecting to another page.


# Update the package lists
sudo apt-get update

# Install Nginx web server
sudo apt-get install -y nginx

# Create an index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define a string for replacement in the Nginx configuration file
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"

# Replace the default server_name configuration with the redirection configuration
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
sudo service nginx restart
