#!/usr/bin/env bash
# Configure a Nginx server so that /redirect_me is redirecting to another page.


# Update the package lists
sudo apt-get update

# Install Nginx web server
sudo apt-get install -y nginx

# Create an index.html file with "Hello World!" content
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

# Define a string for replacement in the Nginx configuration file
to_rep="server_name _;"
rep="\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"

# Replace the default server_name configuration with the redirection configuration
sudo sed -i "s|${to_rep}|${to_rep}${rep}|" /etc/nginx/sites-available/default

# Restart the Nginx service to apply the changes
sudo service nginx restart
