#!/usr/bin/env bash
# This script configures a web server to run Nginx as the 'nginx' user on port 8080.

# The 'sed' command is used to replace '#user www-data' with 'user nginx' in the Nginx configuration file.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# The 'sed' command is also used to replace '80' with '8080' in the default sites-available configuration file.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# The 'chmod' command is used to change the permissions of the Nginx configuration file to '644', 
# which means the owner can read and write to the file, while others can only read it.
chmod 644 /etc/nginx/nginx.conf

# The 'pkill' command is used to terminate the Apache2 process if it is running, 
# as it may interfere with Nginx.
pkill apache2

# Finally, the 'sudo -u nginx service nginx start' command is used to start the Nginx service as the 'nginx' user.
sudo -u nginx service nginx start
