#!/urs/bin/env bash
# This script modifies the Nginx configuration to change the default port and user, and then restarts the Nginx service.
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
