#!/usr/bin/env bash
# This script configures a web server to run Nginx as the 'nginx' user on port 8080.
sed -i "s/#user www-data/user nginx/; s/80/8080/g" /etc/nginx/nginx.conf /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2 || true
sudo -u nginx service nginx start
